name: Build ,test,Scan Docker Image.

on:
  workflow_dispatch:
  

jobs:
  build:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout Code
         uses: actions/checkout@v4

       - name: login into Docker Hub
         uses: docker/login-action@v3
         with: 
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Scan Code at SonarQube
         uses: sonarsource/sonarqube-scan-action@v2
         env:
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         with:
           args: >
             -Dsonar.projectKey=mcdfood
             -Dsonar.projectName=mcdfood
             -Dsonar.sources=.
       
       
       - name: Create the Docker Image 
       - name: Scan the Image by Trivy
       - name: Push to Docker Hub
       
           
         
      
      
